import ILovingMemoryApplicationState from '~/logic/model/ILovingMemoryApplicationState'

const defaultStateObject: ILovingMemoryApplicationState = {
  preferences: {
    appWide: {
      displayOnlyMiddleInitial: true,
    },
    servicePreferences: {
      burial: {
        type: 'burial',
        areHaving: true,
        areLivestreaming: true,
        livestreamIsPublic: false,
      },
      cremation: {
        type: 'cremation',
        areHaving: true,
        areLivestreaming: true,
        livestreamIsPublic: false,
      },
      funeral: {
        type: 'funeral',
        areHaving: true,
        areLivestreaming: true,
        livestreamIsPublic: false,
      },
      scattering: {
        type: 'scattering',
        areHaving: true,
        areLivestreaming: true,
        livestreamIsPublic: false,
      },
    },
  },
  memorialized: {
    first: 'First Name',
    middle: 'Middle Name',
    last: 'Last Name',
    suffix: null,
    prefix: null,
    dateOfBirth: new Date(),
    dateOfDeath: new Date(),
    // lifespanInDays: (dateOfBirth: Date, dateOfDeath: Date) => 0, // move to functions obv
    // lifespanInYears: (lifespanInDays: number) => 0, // move to functions obv
  },
  services: {
    burial: {
      key: 0, // should be generated by `uuid` and correct output obv
      additionalInfo: 'Additional Info about this service here',
      contact: {
        first: 'First Name',
        middle: 'Middle Name',
        last: 'Last Name',
        suffix: null,
        prefix: null,
        phonenumber: '(123)-456-7890',
        email: 'contactperson@emailprovider.org',
        timeZone: {
          name: 'America/New_York',
          offset: -4,
          abbreviation: 'EST',
          isDaylightSavingsTime: false,
          description: 'Eastern Time Zone',
          utc: ['UTC-04:00'],
        },
      },
      livestream: {
        requiresLogin: true,
        url: new URL('https://www.youtube.com/'),
        credentials: {
          username: 'LivestreamUsername',
          password: 'LivestreamPassword',
        },
      },
      location: {
        locationName: 'Name of the location for the burial',
        streetnumber: '123',
        streetName: 'Street Name',
        cityOrProvince: 'City Name',
        state: 'State',
        country: {
          alpha2: 'US',
          alpha3: 'USA',
          name: 'United States of America',
        },
        postalCode: '12345',
        mapURL: new URL('https://www.google.com/maps/'),
        timeZone: {
          name: 'Placeholder Time Zone',
          abbreviation: 'UTC',
          offset: 0,
          isDaylightSavingsTime: false,
          description: 'Time Zone Description',
          utc: [],
        },
      },
      type: 'burial',
      programme: [],
      time: new Date(),
    },
    cremation: {
      key: 0, // should be generated by UUID and correct output obv
      additionalInfo: 'Additional Info about this service here',
      contact: {
        first: 'First Name',
        middle: 'Middle Name',
        last: 'Last Name',
        suffix: null,
        prefix: null,
        phonenumber: '(123)-456-7890',
        email: 'contactperson@emailprovider.org',
        timeZone: {
          name: 'America/New_York',
          offset: -4,
          abbreviation: 'EST',
          isDaylightSavingsTime: false,
          description: 'Eastern Time Zone',
          utc: ['UTC-04:00'],
        },
      },
      livestream: {
        requiresLogin: true,
        url: new URL('https://www.youtube.com/'),
        credentials: {
          username: 'LivestreamUsername',
          password: 'LivestreamPassword',
        },
      },
      location: {
        locationName: 'Name of the location for the cremation',
        streetnumber: '123',
        streetName: 'Street Name',
        cityOrProvince: 'City Name',
        state: 'State',
        country: {
          alpha2: 'US',
          alpha3: 'USA',
          name: 'United States of America',
        },
        postalCode: '12345',
        mapURL: new URL('https://www.google.com/maps/'),
        timeZone: {
          name: 'Placeholder Time Zone',
          abbreviation: 'UTC',
          offset: 0,
          isDaylightSavingsTime: false,
          description: 'Time Zone Description',
          utc: [],
        },
      },
      type: 'cremation',
      programme: [],
      time: new Date(),
    },
    funeral: {
      key: 0, // should be generated by UUID and correct output obv
      additionalInfo: 'Additional Info about this service here',
      contact: {
        first: 'First Name',
        middle: 'Middle Name',
        last: 'Last Name',
        suffix: null,
        prefix: null,
        phonenumber: '(123)-456-7890',
        email: 'contactperson@emailprovider.org',
        timeZone: {
          name: 'America/New_York',
          offset: -4,
          abbreviation: 'EST',
          isDaylightSavingsTime: false,
          description: 'Eastern Time Zone',
          utc: ['UTC-04:00'],
        },
      },
      livestream: {
        requiresLogin: true,
        url: new URL('https://default.url.com/'),
        credentials: {
          username: 'LivestreamUsername',
          password: 'LivestreamPassword',
        },
      },
      location: {
        locationName: 'Name of the location for the funeral',
        streetnumber: '123',
        streetName: 'Street Name',
        cityOrProvince: 'City Name',
        state: 'State',
        country: {
          alpha2: 'US',
          alpha3: 'USA',
          name: 'United States of America',
        },
        postalCode: '12345',
        mapURL: new URL('https://www.google.com/maps/'), // plus whatever query to pull the address up
        timeZone: {
          name: 'Placeholder Time Zone',
          abbreviation: 'UTC',
          offset: 0,
          isDaylightSavingsTime: false,
          description: 'Time Zone Description',
          utc: [],
        },
      },
      type: 'funeral',
      programme: [],
      time: new Date(),
    },
    scattering: {
      key: 0, // should be generated by UUID and correct output obv
      additionalInfo: 'Additional Info about this service here',
      contact: {
        first: 'First Name',
        middle: 'Middle Name',
        last: 'Last Name',
        suffix: null,
        prefix: null,
        phonenumber: '(123)-456-7890',
        email: 'contactperson@emailprovider.org',
        timeZone: {
          name: 'America/New_York',
          offset: -4,
          abbreviation: 'EST',
          isDaylightSavingsTime: false,
          description: 'Eastern Time Zone',
          utc: ['UTC-04:00'],
        },
      },
      livestream: {
        requiresLogin: true,
        url: new URL('https://www.youtube.com/'),
        credentials: {
          username: 'LivestreamUsername',
          password: 'LivestreamPassword',
        },
      },
      location: {
        locationName: 'Name of the location for the scattering of the ashes',
        streetnumber: '123',
        streetName: 'Street Name',
        cityOrProvince: 'City Name',
        state: 'State',
        country: {
          alpha2: 'US',
          alpha3: 'USA',
          name: 'United States of America',
        },
        postalCode: '12345',
        mapURL: new URL('https://www.google.com/maps/'),
        timeZone: {
          name: 'Placeholder Time Zone',
          abbreviation: 'UTC',
          offset: 0,
          isDaylightSavingsTime: false,
          description: 'Time Zone Description',
          utc: [],
        },
      },
      type: 'scattering',
      programme: [],
      time: new Date(),
    },
  },
  charities: [
    {
      name: 'Sample Charity',
      issue: 'makes sure everyone has enough samples',
      url: new URL('https://www.samplecharity.com/'),

    },
  ],
  contentItems: {
    photos: [],
    videos: [],
    songs: [],
    audioClips: [],
  },
}

export default defaultStateObject
