import IContactPerson from './IContactPerson'
import ILivestreamInfo from './ILivestreamInfo'
import ILocation from './ILocation'
import IAgendaItem from './IAgendaItem'
import TServiceType from './TServiceType'

interface IService {
  key: number // should be generated by UUID
  additionalInfo: string
  contact: IContactPerson
  livestream: ILivestreamInfo
  location: ILocation
  type: TServiceType
  programme: IAgendaItem[]
  time: Date
}

export default IService
