// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Charity: typeof import('./components/Charity.vue')['default']
    CharityButton: typeof import('./components/CharityButton.vue')['default']
    CompositionContainer: typeof import('./components/CompositionContainer.vue')['default']
    CopyButton: typeof import('./components/CopyButton.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Livestream: typeof import('./components/Livestream.vue')['default']
    LivestreamCredentials: typeof import('./components/LivestreamCredentials.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    README: typeof import('./components/README.md')['default']
    Service: typeof import('./components/Service.vue')['default']
    ServiceAgendaItem: typeof import('./components/ServiceAgendaItem.vue')['default']
    ServiceProgramme: typeof import('./components/ServiceProgramme.vue')['default']
  }
}

export { }
